# Gateway configuration
spring:
    cloud:
        discovery:
            enabled: true
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
            routes:
                -   id: user-service
                    uri: lb://user-service
                    predicates:
                        - Path=/users/**
                -   id: group-service
                    uri: lb://group-service
                    predicates:
                        - Path=/groups/**
#     Security configuration
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://keycloak:8080/realms/spmia-realm
#     Zipkin configuration
    zipkin:
        baseUrl: http://zipkin:9411
    sleuth:
        sampler:
            percentage: 1

# Actuator monitoring configuration
management:
    server:
        port: 8072
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: '*'

# Eureka configuration
eureka:
    instance:
        hostname: localhost
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/

# Keylock configuration
keycloak:
    realm: spmia-realm
    auth-server-url: http://192.168.1.100:8080/auth
    ssl-required: external
    resource: platform
    credentials:
        secret: NLMpBpyZhwu4pTSCpBuskCeGBZv24p3i
    use-resource-role-mappings: true
    autodetect-bearer-only: true

# Server configuration
server:
    port: 8072
