spring:
    # Database configuration
    datasource:
        url: jdbc:postgresql://database:5432/platform
        hikari:
            username: postgres
            password: password
            driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                default_schema: user_schema
                show_sql: true
                format_sql: true
                hbm2ddl.auto: update
                dialect: org.hibernate.dialect.PostgreSQLDialect
    # Security configuration
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://keycloak:8080/realms/spmia-realm
            client:
                provider:
                    keycloak:
                        issuer-uri: http://keycloak:8080/realms/spmia-realm
                registration:
                    keycloak:
                        client-id: platform
                        client-secret: NLMpBpyZhwu4pTSCpBuskCeGBZv24p3i
                        scope: openid
    # Zipkin configuration
    zipkin:
        baseUrl: http://zipkin:9411
    sleuth:
        sampler:
            percentage: 1
    # Kafka configuration
    kafka:
        producer:
            bootstrap-servers: localhost:9092, localhost:9094, localhost:9096
            acks: all
            properties:
                delivery:
                    timeout:
                        ms: 20000
                linger:
                    ms: 0
                request:
                    timeout:
                        ms: 10000

# Actuator monitoring configuration
management:
    endpoints:
        web:
            exposure:
                include: '*'

# Eureka configuration
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/

# Server configuration
server:
    port: 8081

# Resilence4j configuration
resilience4j.circuitbreaker:
    instances:
        userService:
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitDurationInOpenState: 10s
            failureRateThreshold: 50
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
                - java.util.concurrent.TimeoutException
                - org.springframework.web.client.ResourceAccessException

resilience4j.retry:
    instances:
        retryUserService:
            maxRetryAttempts: 5
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
                - java.util.concurrent.TimeoutException

resilience4j.bulkhead:
    instances:
        bulkheadUserService:
            maxConcurrentCalls: 10
            maxWaitDuration: 10ms

resilience4j.thread-pool-bulkhead:
    instances:
        bulkheadUserService:
            maxThreadPoolSize: 1
            coreThreadPoolSize: 1
            queueCapacity: 1
            keepAliveDuration: 20ms
            writableStackTraceEnabled: true

resilience4j.ratelimiter:
    instances:
        userService:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 100ms
            registerHealthIndicator: true
            eventConsumerBufferSize: 100

resilience4j.timelimiter:
    instances:
        backendA:
            timeoutDuration: 2s
            cancelRunningFuture: true
